### ISSUE TITLE
save to gist

### ISSUE THREAD

**Issue by burritojustice** [whosonfirst/whosonfirst-www-spelunker#69]
would be super helpful to save the geojson bundle to gist (so we can more readily display it in Tangram)

https://developer.github.com/v3/gists/

a few libraries out there but haven't really dug in. but something that could offer to upload anonymously as well as with authentication might be handy?

http://fitzgen.github.io/github-api/
https://gist.github.com/isaacs/5375574

**Comment by thisisaaronland** [comment]
@burritojustice or @stepps00 – do either of you want to take a shot at a PR as a learning exercise? Feel free to unassign yourselves if not.

**Comment by dphiffer** [comment]
Hi @burritojustice, this is up on dev if you wanna test it out:
https://whosonfirst.dev.mapzen.com/spelunker/download/102112179/?exclude=nullisland#14/37.7458/-122.4211

**Comment by thisisaaronland** [comment]
@burritojustice depending on when you read this I may or may not have merged the branch I am working on it to @dphiffer 's work. As of this writing dev is not running his code so if you try things and they don't work poke me and I toggle the relevant branches.

**Comment by dphiffer** [comment]
Here's a preview of what it looks like:

<img width="606" alt="screen shot 2017-07-07 at 11 12 15 pm" src="https://user-images.githubusercontent.com/38114/27964167-eccfbb4a-6369-11e7-9a5c-d8a907d3c8cb.png">

**Comment by nvkelso** [comment]
Can the GIST functionality be a blue button instead of checkbox? (Or just the text link below the blue buttons?)

**Comment by dphiffer** [comment]
Ok, this is back in action on dev.

@nvkelso why not both! Agree that the hyperlink doesn't sit very nicely next to those blue buttons, maybe that could be a blue button.

I like the checkbox here b/c it means you can do all the fussy parts and then you get just one long wait for the bundling to finish, then uploading to GitHub starts right after. If a button is what initiates the upload, you potentially have _two_ coffee runs, since you gotta take action to keep the computers doing the computer stuff.

But that said, maybe two coffee runs are better than one?

**Comment by stepps00** [comment]
I tested the "save to gist" functionality with microhoods in San Francisco and a neighbourhood in Portland - everything works as expected.

This is great!

**Comment by dphiffer** [comment]
Hey, that's good to hear!

I went ahead and changed the checkbox UI into a button. Thinking about it more I realized the flow just makes more sense as two distinct actions, even if it takes a little bit longer.
